### ISSUE TITLE
I'd like to have a try but it failed

### ISSUE THREAD

**Issue by StarXian** [KoenAStam/cytofast#2]
package ‘cytofast’ is not available (for R version 3.5.0)

**Comment by SamGG** [comment]
Hi,
It sounds like cytofast has not been pushed to bioconductor yet. You can try to install from github. If you are already on bioconductor v3.8, use the lazy/easy command `BiocManager::install("KoenAStam/cytofast")`.
Best

**Comment by StarXian** [comment]
Thank you so much .
By the way, do you have the whole pipeline of the analysis? I'm newer and don't know how to use it, but I have cytof data and I like to have a try.


| |
厦门大学贾贤
|
|
xmujiaxian@163.com
|
签名由网易邮箱大师定制
On 11/20/2018 16:34，Samuel Granjeaud<notifications@github.com> wrote：

Hi,
It sounds like cytofast has not been pushed to bioconductor yet. You can try to install from github. If you are already on bioconductor v3.8, use the lazy/easy command BiocManager::install("KoenAStam/cytofast").
Best

**Comment by SamGG** [comment]
Your question sounds easy to solve, that's why I answered. But I didn't test cytofast yet.
Best.

**Comment by KoenAStam** [comment]
Hi @CyTOF,

Let me anwser all your questions. First, cytofast is still under development, but we are currently submitting the package to bioconductor, so stay tuned. If you want to work with the development package you can install the package from github with _devtools::install_github("KoenAStam/cytofast")_. Or like SamGG suggested, _BiocManager::install("KoenAStam/cytofast")_.

Second, There is indeed a workflow we published just recently: https://www.ncbi.nlm.nih.gov/pmc/articles/PMC6226576/. Also have a look at the vignette, which you can find in the github repo. 

If you have any questions, just let me know!

**Comment by SamGG** [comment]
@KoenAStam What is the input of cytofast: the clusters annotated/selected by the user **or** all the clusters at any level of hierarchy of the HSNE result? I think the input is the selected clusters. I think the comparison to citrus (as stated in the article) holds if all nodes of all levels are exported and analyzed. That's just my very own opinion.

**Comment by KoenAStam** [comment]
@SamGG The basic idea is that the input comes from Cytosplore (https://www.cytosplore.org/), and then all clusters on a certain HSNE level (It is also possible to combine, or split, levels later on). However, we also show how to use different clustering algorithms, such as FlowSOM. 

I think there are already some workflow tools, like Citrus and cytoWorkflow (and probably more), hence the similarities. However, we do use Cytosplore in-house a lot and therefore we wanted to make this package. We are also planning to add more analysis functionality, such as the globaltest and some graphical modelling. Thus we think that cytofast can still contribute. Also, the focus of the package is a bit more tuned to lesser experienced R-users. 

I hope this answers your question.

**Comment by StarXian** [comment]
Great! Thank you so much for all your guys help, I'm a lesser experienced R-user, I know the package because I have read the paper which published recently. But I still don't know how to use it, I hope to follow a example as cytofkit did.They have the example on github and I can analysis my data follow it.


| |
厦门大学贾贤
|
|
xmujiaxian@163.com
|
签名由网易邮箱大师定制
On 11/22/2018 20:52，KoenAStam<notifications@github.com> wrote：

@SamGG The basic idea is that the input comes from Cytosplore (https://www.cytosplore.org/), and then all clusters on a certain HSNE level (It is also possible to combine, or split, levels later on). However, we also show how to use different clustering algorithms, such as FlowSOM.

I think there are already some workflow tools, like Citrus and cytoWorkflow (and probably more), hence the similarities. However, we do use Cytosplore in-house a lot and therefore we wanted to make this package. We are also planning to add more analysis functionality, such as the globaltest and some graphical modelling. Thus we think that cytofast can still contribute. Also, the focus of the package is a bit more tuned to lesser experienced R-users.

I hope this answers your question.

**Comment by SamGG** [comment]
Thanks for your reply.
My point was only concerning the multi-level analysis performed within citrus. A down side is that citrus does not consider the combinations of clusters that are in different branches and this could lead to miss some interesting discoveries. But combining different populations deals with multi-variate data analysis which is a vast field.
I don't want to discuss extensively the second point you raised. From my experience of twenty years in computational biology, I will point a single fact. How many packages remain in the micro-array field?  I would say limma. I think it would be valuable **for the end users** (especially un-experienced) that **we programmers/analysts** put our efforts in the same project. That's one reason why I contribute to the package of others. From a trainer point of view, I clearly see how difficult it could be for those users to deal with different packages. To be noted, the simplification of the cytofWorkflow of MD Robinson's group is currently in progress. Let's start a consortium ;-)
Best.

**Comment by KoenAStam** [comment]
I couldn't agree more; Collaboration is key to succes! I must admit that one of main reasons I started with bundling this package was the learning experience, I thought it was a nice new challenge. The other reason is that we wanted a fast workflow (from Cytosplore) to identify some potential cell subsets that are of importance. So I was mainly designing some handy and accessible scripts for our group, but we got encouraged to put 'out there'.
